import { StyleSheet } from '@react-pdf/renderer';

export const colors = {
  primary: '#0ea5e9',
  primaryDark: '#0369a1',
  teal: '#14b8a6',
  emerald: '#10b981',
  amber: '#f59e0b',
  red: '#ef4444',
  slate600: '#475569',
  slate400: '#94a3b8',
  white: '#ffffff',
  bgLight: '#f8fafc',
  bgSection: '#f1f5f9',
};

export const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    padding: 32,
    backgroundColor: colors.white,
    color: colors.slate600,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: colors.primary,
    paddingBottom: 10,
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: colors.primaryDark,
  },
  headerSubtitle: {
    fontSize: 10,
    color: colors.slate400,
    marginTop: 2,
  },
  logo: {
    width: 80,
    height: 30,
    objectFit: 'contain',
  },
  sectionRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  section: {
    flex: 1,
    backgroundColor: colors.bgSection,
    borderRadius: 6,
    padding: 10,
  },
  sectionFull: {
    backgroundColor: colors.bgSection,
    borderRadius: 6,
    padding: 10,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: colors.primary,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.primary,
    paddingBottom: 4,
  },
  fieldRow: {
    flexDirection: 'row',
    marginBottom: 3,
  },
  fieldLabel: {
    fontFamily: 'Helvetica-Bold',
    color: colors.slate600,
    width: 90,
    fontSize: 9,
  },
  fieldValue: {
    flex: 1,
    fontSize: 9,
    color: colors.slate600,
  },
  costsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  costBox: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: colors.bgSection,
    borderRadius: 6,
    padding: 8,
    alignItems: 'center',
  },
  costBoxTotal: {
    width: '100%',
    backgroundColor: '#ccfbf1',
    borderRadius: 6,
    padding: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.teal,
  },
  costLabel: {
    fontSize: 8,
    color: colors.primary,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  costValue: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: colors.emerald,
  },
  costValueTotal: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: colors.teal,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: colors.primary,
    padding: 5,
    borderRadius: 4,
    marginBottom: 2,
  },
  tableHeaderCell: {
    fontFamily: 'Helvetica-Bold',
    color: colors.white,
    fontSize: 9,
  },
  tableRow: {
    flexDirection: 'row',
    padding: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  tableCell: {
    fontSize: 9,
    color: colors.slate600,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: colors.white,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 32,
    right: 32,
    textAlign: 'center',
    fontSize: 8,
    color: colors.slate400,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 6,
  },
});
